# Generated by Django 4.2.6 on 2023-10-24 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('idMoneda', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=5)),
                ('simbolo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa_de_cambio', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fecha_actualizacion', models.DateField()),
                ('moneda_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasas_destino', to='authApp.moneda')),
                ('moneda_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasas_origen', to='authApp.moneda')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_origen', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_destino', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_conversion', models.DateTimeField(auto_now_add=True)),
                ('moneda_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversiones_destino', to='authApp.moneda')),
                ('moneda_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversiones_origen', to='authApp.moneda')),
            ],
        ),
    ]
